-- =============================================================
-- Petpooja AI Copilot — Supabase PostgreSQL Schema
-- =============================================================
-- Run this in Supabase SQL Editor to create all tables.
-- Or let SQLAlchemy create them via Base.metadata.create_all()
-- =============================================================

-- Drop existing tables (in dependency order)
DROP TABLE IF EXISTS combo_suggestions CASCADE;
DROP TABLE IF EXISTS kots CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS sale_transactions CASCADE;
DROP TABLE IF EXISTS menu_items CASCADE;
DROP TABLE IF EXISTS categories CASCADE;

-- ── Categories ──────────────────────────────────

CREATE TABLE categories (
    id          SERIAL PRIMARY KEY,
    name        VARCHAR(100) UNIQUE NOT NULL,
    name_hi     VARCHAR(100),
    display_order INTEGER DEFAULT 0,
    is_active   BOOLEAN DEFAULT TRUE
);

CREATE INDEX idx_categories_active ON categories (is_active);

-- ── Menu Items ──────────────────────────────────

CREATE TABLE menu_items (
    id              SERIAL PRIMARY KEY,
    name            VARCHAR(200) NOT NULL,
    name_hi         VARCHAR(200),
    description     TEXT,
    aliases         TEXT DEFAULT '',          -- pipe-separated: "pnr tikka|panir tikka"
    category_id     INTEGER REFERENCES categories(id) ON DELETE SET NULL,
    selling_price   FLOAT NOT NULL,
    food_cost       FLOAT NOT NULL,
    modifiers       JSONB DEFAULT '{}',       -- {"spice_level": [...], "size": [...]}
    is_veg          BOOLEAN DEFAULT TRUE,
    is_available    BOOLEAN DEFAULT TRUE,
    is_bestseller   BOOLEAN DEFAULT FALSE,
    current_stock   INTEGER,                  -- NULL = unlimited
    tags            JSONB DEFAULT '[]',       -- ["spicy", "chef-special"]
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_menu_items_category ON menu_items (category_id);
CREATE INDEX idx_menu_items_available ON menu_items (is_available);
CREATE INDEX idx_menu_items_bestseller ON menu_items (is_bestseller);

-- ── Sale Transactions (historical order data for analytics) ──

CREATE TABLE sale_transactions (
    id          SERIAL PRIMARY KEY,
    item_id     INTEGER NOT NULL REFERENCES menu_items(id) ON DELETE CASCADE,
    order_id    VARCHAR(50) NOT NULL,
    quantity    INTEGER DEFAULT 1,
    unit_price  FLOAT NOT NULL,
    total_price FLOAT NOT NULL,
    order_type  VARCHAR(20) DEFAULT 'dine_in',   -- dine_in | takeaway | delivery
    sold_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_sales_item ON sale_transactions (item_id);
CREATE INDEX idx_sales_order ON sale_transactions (order_id);
CREATE INDEX idx_sales_sold_at ON sale_transactions (sold_at);

-- ── Orders (voice/manual orders) ────────────────

CREATE TABLE orders (
    id              SERIAL PRIMARY KEY,
    order_id        VARCHAR(50) UNIQUE NOT NULL,
    order_number    VARCHAR(20),
    total_amount    FLOAT DEFAULT 0.0,
    status          VARCHAR(20) DEFAULT 'building',  -- building | confirmed | cancelled
    order_type      VARCHAR(20) DEFAULT 'dine_in',
    table_number    VARCHAR(10),
    source          VARCHAR(20) DEFAULT 'voice',     -- voice | manual
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_orders_status ON orders (status);
CREATE INDEX idx_orders_created ON orders (created_at DESC);

-- ── Order Items ─────────────────────────────────

CREATE TABLE order_items (
    id                  SERIAL PRIMARY KEY,
    order_id            VARCHAR(50) NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    item_id             INTEGER NOT NULL REFERENCES menu_items(id) ON DELETE CASCADE,
    quantity            INTEGER DEFAULT 1,
    unit_price          FLOAT NOT NULL,
    modifiers_applied   JSONB DEFAULT '{}',
    line_total          FLOAT NOT NULL
);

CREATE INDEX idx_order_items_order ON order_items (order_id);

-- ── KOT (Kitchen Order Tickets) ─────────────────

CREATE TABLE kots (
    id              SERIAL PRIMARY KEY,
    kot_id          VARCHAR(50) UNIQUE NOT NULL,    -- KOT-YYYYMMDD-XXXX
    order_id        VARCHAR(50) NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    items_summary   JSONB NOT NULL,                 -- [{name, qty, modifiers}]
    print_ready     TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_kots_order ON kots (order_id);

-- ── Combo Suggestions (generated by FP-Growth) ──

CREATE TABLE combo_suggestions (
    id                  SERIAL PRIMARY KEY,
    name                VARCHAR(200) NOT NULL,
    item_ids            JSONB NOT NULL,             -- [1, 5, 12]
    item_names          JSONB NOT NULL,             -- ["Paneer Tikka", "Naan"]
    individual_total    FLOAT,
    combo_price         FLOAT,
    discount_pct        FLOAT,
    expected_margin     FLOAT,
    support             FLOAT,
    confidence          FLOAT,
    lift                FLOAT,
    combo_score         FLOAT,
    created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- ── Enable Row-Level Security (optional, recommended) ──

-- ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE sale_transactions ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE kots ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE combo_suggestions ENABLE ROW LEVEL SECURITY;

-- ── Done ──
SELECT 'Schema created successfully' AS status;
